---
title: "eww "
author: Louie Anderson
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}
library(knitr)

# As long as you are working in a Rstudio Project file, you shouldn't need to 'hard code' directories like this 
# change to your own working directory
#knitr::opts_knit$set(root.dir = 'C:/Users/doosti/Desktop/MGSC_310')

# set seed to your own favorite number
set.seed(765)
options(width=70)
# if you want to prevent scientific format for numbers use this:

options(scipen=99)

# general rchunk code options
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=FALSE, size = "vsmall")
opts_chunk$set(message = FALSE,
               warning = FALSE,
               cache = TRUE,
               autodep = TRUE,
               cache.comments = FALSE,
               collapse = TRUE,
               fig.width = 5,  
               fig.height = 4,
               fig.align='center')


```

```{r setup_2}

# load all your libraries here
library('tidyverse')
library('rsample')
library('tree')
library('caret')
library('ggplot2')
library('glmnet')
library('glmnetUtils')
library('randomForest')
library('ggcorrplot') 
library('caTools')
library('car')

# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 
```



```{r}
Cost <- read.csv("datasets/media prediction and its cost.csv")
Cost %>% glimpse()

set.seed(765)

CostC <- Cost[-sample(1:nrow(Cost), 55428), ]
CostClean<- CostC %>% mutate(food_category = fct_lump_min(food_category,125),
                             food_department= fct_lump_min(food_department,175),
                             promotion_name = fct_lump_min(promotion_name,125),
                             brand_name = fct_lump_min(brand_name,85),
                             store_city = fct_lump_min(store_city,100),
                             store_type = fct_lump_min(store_type, 550),
                             store_state = fct_lump_min(store_state, 700))

CostClean<- CostClean %>% mutate(food_category = as.factor(food_category),
                                 food_department= as.factor(food_department),
                                 food_family = as.factor(food_family),
                                 promotion_name = as.factor(promotion_name),
                                 sales_country = as.factor(sales_country),
                                 marital_status = as.factor(marital_status),
                                 education = as.factor(education),
                                 member_card = as.factor(member_card),
                                 occupation = as.factor(occupation),
                                 houseowner = as.factor(houseowner),
                                 brand_name = as.factor(brand_name),
                                 recyclable_package = as.factor(recyclable_package),
                                 low_fat = as.factor(low_fat),
                                 store_type = as.factor(store_type),
                                 store_city = as.factor(store_city),
                                 store_state = as.factor(store_state),
                                 coffee_bar = as.factor(coffee_bar),
                                 video_store = as.factor(video_store),
                                 salad_bar = as.factor(salad_bar),
                                 prepared_food = as.factor(prepared_food),
                                 florist = as.factor(florist),
                                 media_type = as.factor(media_type),
                                 avg..yearly_income = as.factor(avg..yearly_income))
CostClean<- CostClean[,-30:-38]

view(CostClean)

```



```{r}

#Summary Stats
CostClean %>%  glimpse()
summary(CostClean)

```


```{r}

#Splitting Data
CostSplit <- initial_split(CostClean, prop=0.8)
CostTrain <- training(CostSplit)
CostTest <- testing(CostSplit)

#4,000 training, 1,000 testing
```


```{r}
#Model for linear regression
CostModel <- lm(cost ~., data = CostTrain)
summary(CostModel)


### These are not part of the code, just a way for me to fix most of the NAs###
#vif(CostModel) #Multicollinearity problem
#test <- lm(cost~ video_store + prepared_food + coffee_bar + salad_bar + florist, data = CostTrain)
#vif(test) #Most likely these variables, need to drop due to multicollinearity

#Dropping suspected multicollinearity variables
#CostClean2 <- CostClean[,-30:-38]
#view(CostClean2)
#CostModel2 <- lm(cost~., data = CostClean2)
#summary(CostModel2)
###


#Predictions train and test
predCostTrain <-  predict(CostModel, newdata = CostTrain)

predCostTest <- predict(CostModel, newdata = CostTest)
```



```{r}
#RMSE calculation
RMSE(predCostTrain, CostTrain$cost)

#[1] 26.49515
RMSE(predCostTest, CostTest$cost)

#[1] 26.43256
```
```{r}
#Creating Random Forest Model
costRF<- randomForest(cost~.,
                           data = CostTrain,
                           ntree = 500,
                           mtry = 20,
                           importance = TRUE)

print(costRF)
plot(costRF)

#Calculating performance
Cost_RF_train<-  predict(costRF, newdata = CostTrain)
Cost_RF_test <- predict(costRF, newdata = CostTest)

RMSE(Cost_RF_train, CostTrain$cost)

#[1] 5.347212

RMSE(Cost_RF_test, CostTest$cost)

#[1] 13.38895
```

```{r}
#Variable importance
importance <- importance(costRF)


# importance plot
plot(importance)
varImpPlot(costRF)
```


```{r}
#Model for Decision Tree
CostTModel <- tree(cost~., data = CostTrain)

plot(CostTModel)
text(CostTModel, digits = 2, pretty = 0 ,cex = .65)

#Predicting train and test
predCostTTrain <- predict(CostTModel, newdata = CostTrain)

predCostTTest <- predict(CostTModel, newdata = CostTest)

#RMSE Calculation
RMSE(predCostTTrain, CostTrain$cost)

#[1] 22.14885

RMSE(predCostTTest, CostTest$cost)

#[1] 22.46054

```

```{r}
#Finding the best tree size
cv.cost <- cv.tree(CostTModel)

print(cv.cost)

#Plotting the errors
plot(cv.cost$size, cv.cost$dev, type = "b")

#Pruning the tree using 16 as size
pruned_cost <-  prune.tree(CostTModel, best = 16)

#Predicting pruned model
predict_Cost_train <- predict(pruned_cost, newdata = CostTrain)
RMSE(predict_Cost_train, CostTrain$cost)

#[1] 22.12956

predict_Cost_test <- predict(pruned_cost, newdata = CostTest)
RMSE(predict_Cost_test, CostTest$cost)

#[1] 22.49857
```
