---
title: "Problem Set 4"
author: "Karen Ngo"
subtitle: MGSC 310 Problem Set Template
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}


library(knitr)

# As long as you are working in a Rstudio Project file, you shouldn't need to 'hard code' directories like this
# change to your own working directory
#knitr::opts_knit$set(root.dir = 'C:/Users/doosti/Desktop/MGSC_310')



options(width=70)
# if you want to prevent scientific format for numbers use this:
options(scipen=99)

# general rchunk code options
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=FALSE, size = "vsmall")
opts_chunk$set(message = FALSE,
               warning = FALSE,
               cache = TRUE,
               autodep = TRUE,
               cache.comments = FALSE,
               collapse = TRUE,
               fig.width = 5,
               fig.height = 4,
               fig.align='center')

```

```{r setup_2}

# load all your libraries here
library('tidyverse')
library('rsample')
library(tree)
library(ggridges)
library(caret)
# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 

```


## Question a

a) Use the IMDB 5000 dataset and the following code to clean and prepare the dataset for modeling.


```{r}

Cost <- read.csv("datasets/media prediction and its cost.csv")
Cost %>% glimpse()

CostC <- Cost[-sample(1:nrow(Cost), 55428), ]
CostClean<- CostC %>% mutate(food_category = fct_lump_min(food_category,125),
                             food_department= fct_lump_min(food_department,175),
                             promotion_name = fct_lump_min(promotion_name,125),
                             brand_name = fct_lump_min(brand_name,85),
                             store_city = fct_lump_min(store_city,100))

CostClean<- CostClean %>% mutate(food_category = as.factor(food_category),
                             food_department= as.factor(food_department),
                             food_family = as.factor(food_family),
                             promotion_name = as.factor(promotion_name),
                             sales_country = as.factor(sales_country),
                             marital_status = as.factor(marital_status),
                             education = as.factor(education),
                             member_card = as.factor(member_card),
                             occupation = as.factor(occupation),
                             houseowner = as.factor(houseowner),
                             brand_name = as.factor(brand_name),
                             recyclable_package = as.factor(recyclable_package),
                             low_fat = as.factor(low_fat),
                             store_type = as.factor(store_type),
                             store_city = as.factor(store_city),
                             store_state = as.factor(store_state),
                             coffee_bar = as.factor(coffee_bar),
                             video_store = as.factor(video_store),
                             salad_bar = as.factor(salad_bar),
                             prepared_food = as.factor(prepared_food),
                             florist = as.factor(florist),
                             media_type = as.factor(media_type))

#Summary Stats
CostClean %>%  glimpse()
summary(CostClean)
view(CostClean)
                               




```


```{r}

set.seed(765)
cost_split <- initial_split(CostClean, prop=0.8)
cost_train <- training(cost_split)
cost_test <- testing(cost_split)

```

LINEAR REGRESSION (NORMAL)
```{r}

model = lm(cost ~., 
           data = cost_train)

summary(model)

```

```{r}

predict_train <- predict(model, newdata=cost_train)
predict_test <- predict(model, newdata=cost_test)

```

```{r}

rmse_train <- RMSE(predict_train, cost_train$cost)
rmse_test <- RMSE(predict_test, obs = cost_test$cost)

rmse_train
rmse_test

```

DECISION TREE

```{r}

tree_cost <- tree(cost ~., data = cost_train)
plot(tree_cost)
text(tree_cost, digit=2, pretty = 0, cex=0.5)


```
```{r}

predict_cost_train <- predict(tree_cost, newdata=cost_train)
predict_cost_test <- predict(tree_cost, newdata=cost_test)

rmse_tree_train <- RMSE(predict_cost_train, cost_train$cost)
rmse_tree_test <- RMSE(predict_cost_test, cost_test$cost)

rmse_tree_train
rmse_tree_test

```


```{r}

cv.tree_cost <- cv.tree(tree_cost)
cv.tree_cost
plot(cv.tree_cost$size, cv.tree_cost$dev, type = 'b')

```
```{r}

size <- cv.tree_cost$size[which.min(cv.tree_cost$dev)]

pruned_tree_cost <- prune.tree(tree_cost, best = size)

prune_predict_cost_train <- predict(pruned_tree_cost, newdata=cost_train)
prune_predict_cost_test <- predict(pruned_tree_cost, newdata=cost_test)

prune_rmse_tree_train <- RMSE(prune_predict_cost_train, cost_train$cost)
prune_rmse_tree_test <- RMSE(prune_predict_cost_test, cost_test$cost)

prune_rmse_tree_train
prune_rmse_tree_test

```





