---
title: "Final Project"
author: "Angel Hernandez"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/ahern/OneDrive - Chapman University/Desktop/MGSC_310")
```

```{r}
library('tidyverse')
Cost <- read.csv("datasets/media prediction and its cost.csv")
Cost %>% glimpse()

CostC <- Cost[-sample(1:nrow(Cost), 55428), ]
CostClean<- CostC %>% mutate(food_category = fct_lump_min(food_category,125),
                             food_department= fct_lump_min(food_department,175),
                             promotion_name = fct_lump_min(promotion_name,125),
                             brand_name = fct_lump_min(brand_name,85),
                             store_city = fct_lump_min(store_city,100))

CostClean<- CostClean %>% mutate(food_category = as.factor(food_category),
                             food_department= as.factor(food_department),
                             food_family = as.factor(food_family),
                             promotion_name = as.factor(promotion_name),
                             sales_country = as.factor(sales_country),
                             marital_status = as.factor(marital_status),
                             education = as.factor(education),
                             member_card = as.factor(member_card),
                             occupation = as.factor(occupation),
                             houseowner = as.factor(houseowner),
                             brand_name = as.factor(brand_name),
                             recyclable_package = as.factor(recyclable_package),
                             low_fat = as.factor(low_fat),
                             store_type = as.factor(store_type),
                             store_city = as.factor(store_city),
                             store_state = as.factor(store_state),
                             coffee_bar = as.factor(coffee_bar),
                             video_store = as.factor(video_store),
                             salad_bar = as.factor(salad_bar),
                             prepared_food = as.factor(prepared_food),
                             florist = as.factor(florist),
                             media_type = as.factor(media_type))

#Summary Stats
CostClean %>%  glimpse()
summary(CostClean)
view(CostClean)
```


```{r}
# Linear Regression Model
library('rsample')
library(caret)
set.seed(765)
CostClean_split <- initial_split(CostClean, 0.8)
CostClean_train <- training(CostClean_split)
CostClean_test <- testing(CostClean_split)

model1 <- lm(cost~., data = CostClean_train)

summary(model1)

predict_train <- predict(model1, newdata = CostClean_train)
predict_test <- predict(model1, newdata = CostClean_test)

RMSE(pred = predict_train, CostClean_train$cost)
# [1] 26.27025
RMSE(pred = predict_test, CostClean_test$cost)
# [1] 26.93851
```

```{r}
library('tidyverse')
library('rsample')
library('glmnet')
library('glmnetUtils')
library('forcats')
# lasso Model
lasso_mod <- cv.glmnet(cost ~ .,
                       data = CostClean_train,
                       # note alpha = 1 sets Lasso!  
                       alpha = 1)
summary(lasso_mod)

print(lasso_mod$lambda.min)
#
print(lasso_mod$lambda.1se)

coef(lasso_mod, s = lasso_mod$lambda.min) %>% 
  round(3)

lasso_coefs <- data.frame(
  lasso_min = coef(lasso_mod, s = lasso_mod$lambda.min) %>% 
    round(3) %>% as.matrix() ,
  lasso_1se = coef(lasso_mod, s = lasso_mod$lambda.1se) %>% 
    round(3) %>% as.matrix() 
) %>% rename(lasso_min = 1, lasso_1se = 2)

print(lasso_coefs)
summary(lasso_coefs)
library('coefplot')

coefpath(lasso_mod)

lasso_coefs %>% 
  select(lasso_min) %>% 
  filter(lasso_min != 0) %>% 
  nrow()

# for lambda.1se
lasso_coefs %>% 
  select(lasso_1se) %>% 
  filter(lasso_1se != 0) %>% 
  nrow()

predict_train_lasso <- predict(lasso_mod, s=lasso_mod$lambda.min, CostClean_train)
predict_test_lasso <- predict(lasso_mod, s=lasso_mod$lambda.min, CostClean_test)

print(predict_train_lasso)
print(predict_test_lasso)

RMSE(pred = predict_train_lasso, CostClean_train$cost)
# [1] 26.45705
RMSE(pred = predict_test_lasso, CostClean_test$cost)
# [1] 26.84907
```

```{r}
# Tree Model
library(tree)
library('forcats')

tree_mod <- tree(cost ~ .,
                 data = CostClean_train)

plot(tree_mod)
text(tree_mod, digit = 2, pretty = 0, cex = 0.25)


# finding predicted values for train and test set based on the tree model
predicted_train <- predict(tree_mod, newdata = CostClean_train)
predicted_test <- predict(tree_mod, newdata = CostClean_test)

# Finding the error on each set
RMSE(pred = predicted_train, CostClean_train$cost)
# [1] 21.52555
RMSE(pred = predicted_test, CostClean_test$cost)
# [1] 22.22936
```
